- name: Software | Install MesloLGS
  tags: software,fonts
  changed_when: false
  shell: |
    mkdir -p ~/.local/share/fonts

    curl https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf -s -L --output "$HOME/.local/share/fonts/MesloLGS NF Regular.ttf"
    curl https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf -s -L --output "$HOME/.local/share/fonts/MesloLGS NF Bold.ttf"
    curl https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf -s -L --output "$HOME/.local/share/fonts/MesloLGS NF Italic.ttf"
    curl https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf -s -L --output "$HOME/.local/share/fonts/MesloLGS NF Bold Italic.ttf"
