- name: Software | Utility | Check if Pamac is installed
  shell: which pamac
  register: pamac_check
  failed_when: pamac_check.rc > 1

- name: Software | Utility | Pamac Pre-requisites (Arch)
  tags: software,utility
  when: pamac_check.rc == 1
  pacman:
    name: base-devel
    state: present

- name: Software | Utility | Clone Pamac Repository (Arcg)
  tags: software,utility
  when: pamac_check.rc == 1
  git:
    repo: https://aur.archlinux.org/pamac-aur.git
    dest: /tmp/ansible/pamac-aur

- name: Software | Utility | Install Pamac (Arch)
  tags: software,utility
  when: pamac_check.rc == 1
  shell: cd /tmp/ansible/pamac-aur && makepkg -sic --noconfirm
