- name: Software | Install ProtonVPN (APT, DNF)
  become: true
  ignore_errors: true
  when: ansible_pkg_mgr in ["apt", "dnf",  "yum"]
  package:
    name: protonvpn

- name: Software | Install ProtonVPN-CLI (Arch)
  become: true
  ignore_errors: true
  when: ansible_pkg_mgr in ["pacman"]
  pacman:
    name: protonvpn-cli
    executable: yay
    extra_args: --builddir /var/cache/yay
